---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-self-service-web
  namespace: engineering
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /whitelist
        backend:
          serviceName: das-self-service
          servicePort: 80
