---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-self-service
    service: das-tool-service
  name: das-self-service
  namespace: {{Namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-self-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-self-service
    service: das-tool-service
  name: das-self-service
  namespace: {{Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-self-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: das-self-service
        service: das-tool-service
    spec:
      containers:
      - env:
        - name: LoggingRedisConnectionString
          value: {{LoggingRedisConnectionString}}
        - name: LoggingRedisKey
          value: logstash
        - name: EnvironmentName
          value: {{EnvironmentName}}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: {{WebAppInsightsInstrumentationkey}}
        - name: Cdn__Url
          value: {{CdnUrl}}
        - name: BaseUrl
          value: {{IngressHost}}
        - name: RedisConnectionString
          value: {{RedisConnectionString}}
        - name: VstsConfig__CollectionUri
          value: {{CollectionUri}}
        - name: VstsConfig__ProjectName
          value: {{ProjectName}}
        - name: VstsConfig__PatToken
          value: {{PatToken}}
        - name: VstsConfig__RequiredRole
          value: {{RequiredRole}}

        image: {{WebImage}}
        imagePullPolicy: IfNotPresent
        name: das-self-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
