---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-self-service
    service: das-tool-service
  name: das-self-service
  namespace: {{KubernetesNamespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-self-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-self-service
    service: das-tool-service
  name: das-self-service
  namespace: {{KubernetesNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-self-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: das-self-service
        service: das-tool-service
    spec:
      nodeSelector:
        agentpool: tools01
      containers:
      - env:
        - name: VstsConfig__CollectionUri
          value: {{AzureDevopsOrganisationUrl}}
        - name: VstsConfig__ProjectName
          value: {{AzureDevopsProjectName}}
        - name: VstsConfig__PatToken
          value: {{SelfServicePatToken}}
        - name: RequiredRole
          value: {{SelfServiceRequiredRole}}
        image: {{PublicAcrName}}.azurecr.io/{{ContainerImageName}}:{{BuildNumber}}
        imagePullPolicy: IfNotPresent
        name: das-self-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
        envFrom:
          - configMapRef:
              name: das-tool-service-shared-config
        readinessProbe:
          httpGet:
            path: "/whitelist/health"
            port: 80
          periodSeconds: 10
          timeoutSeconds: 1
      volumes:
        - name: shared-app-settings
          configMap:
            name: das-tool-service-shared-config
